PLAYER_NATION: dict[str, str] = {
    "abdulaziz hatem": "qat",
    "ahmed fathi": "qat",
    "alexander isak": "swe",
    "alexander srloth": "nor",
    "alexis mac allister": "arg",
    "alphonso davies": "can",
    "amad diallo": "civ",
    "anthony elanga": "swe",
    "antoine semenyo": "gha",
    "antonio rudiger": "ger",
    "arda guler": "tur",
    "aurelien tchouameni": "fra",
    "bernardo silva": "prt",
    "bradley barcola": "fra",
    "brahim diaz": "mar",
    "breel embolo": "che",
    "bruno fernandes": "prt",
    "bruno guimaraes": "bra",
    "bukayo saka": "eng",
    "carney chukwuemeka": "aut",
    "casemiro": "bra",
    "charles de ketelaere": "bel",
    "che adams": "sco",
    "chris wood": "nzl",
    "christian pulisic": "usa",
    "cody gakpo": "nld",
    "cole palmer": "eng",
    "cristiano ronaldo": "prt",
    "dan ndoye": "che",
    "dani olmo": "esp",
    "darwin nunez": "ury",
    "david raya": "esp",
    "declan rice": "eng",
    "denzel dumfries": "nld",
    "desire doue": "fra",
    "donyell malen": "nld",
    "eberechi eze": "eng",
    "emiliano buendia": "arg",
    "endrick": "bra",
    "enzo fernandez": "arg",
    "erling haaland": "nor",
    "fabian ruiz": "esp",
    "federico valverde": "ury",
    "fermin lopez": "esp",
    "ferran torres": "esp",
    "florian wirtz": "ger",
    "folarin balogun": "usa",
    "frenkie de jong": "nld",
    "gabriel magalhaes": "bra",
    "gabriel martinelli": "bra",
    "gavi": "esp",
    "goncalo ramos": "prt",
    "granit xhaka": "che",
    "haissem hassan": "egy",
    "hakan calhanoglu": "tur",
    "harry kane": "eng",
    "ibrahim sangare": "civ",
    "ibrahima konate": "fra",
    "igor thiago": "bra",
    "iliman ndiaye": "sen",
    "inaki williams": "gha",
    "ismael diaz": "pan",
    "ismaila sarr": "sen",
    "ivan perisic": "hrv",
    "jamal musiala": "ger",
    "james rodriguez": "col",
    "jeremie frimpong": "nld",
    "jeremy doku": "bel",
    "joao cancelo": "prt",
    "joao neves": "prt",
    "joao pedro": "bra",
    "joshua kimmich": "ger",
    "josko gvardiol": "hrv",
    "josue casimir": "hai",
    "jude bellingham": "eng",
    "jules kounde": "fra",
    "julian alvarez": "arg",
    "julio enciso": "par",
    "kai havertz": "ger",
    "kaoru mitoma": "jpn",
    "keito nakamura": "jpn",
    "kenan yldz": "tur",
    "kevin de bruyne": "bel",
    "khalil ayari": "tun",
    "kim min-jae": "kor",
    "kylian mbappe": "fra",
    "lamine yamal": "esp",
    "lautaro martinez": "arg",
    "leandro trossard": "bel",
    "lennart kahl": "ger",
    "leroy sane": "ger",
    "lionel messi": "arg",
    "lisandro martinez": "arg",
    "luis diaz": "col",
    "luis javier suarez": "col",
    "luis suarez": "ury",
    "luka modric": "hrv",
    "marc cucurella": "esp",
    "marc guehi": "eng",
    "marcel sabitzer": "aut",
    "marcus rashford": "eng",
    "marcus thuram": "fra",
    "marquinhos": "bra",
    "martin degaard": "nor",
    "martin zubimendi": "esp",
    "mateo kovacic": "hrv",
    "matheus cunha": "bra",
    "memphis depay": "nld",
    "michael olise": "fra",
    "miguel almiron": "par",
    "mikel merino": "esp",
    "mikel oyarzabal": "esp",
    "mohamed salah": "egy",
    "moises caicedo": "ecu",
    "n'golo kante": "fra",
    "neymar": "bra",
    "neymar jr.": "bra",
    "nick woltemade": "ger",
    "nico williams": "esp",
    "nicolas pepe": "civ",
    "noah okafor": "che",
    "nuno mendes": "prt",
    "omar marmoush": "egy",
    "oscar bobb": "nor",
    "ousmane dembele": "fra",
    "pau cubarsi": "esp",
    "pedri": "esp",
    "pedro neto": "prt",
    "pervis estupinan": "ecu",
    "phil foden": "eng",
    "rafael leao": "prt",
    "raphinha": "bra",
    "raul jimenez": "mex",
    "rayan cherki": "fra",
    "reece james": "eng",
    "ricardo pepi": "usa",
    "rodri": "esp",
    "romelu lukaku": "bel",
    "ruben dias": "prt",
    "ryan gravenberch": "nld",
    "sadio mane": "sen",
    "scott mctominay": "sco",
    "son heung-min": "kor",
    "tahith chong": "kor",
    "takefusa kubo": "jpn",
    "teun koopmeiners": "nld",
    "tijjani reijnders": "nld",
    "trent alexander-arnold": "eng",
    "viktor gyokeres": "swe",
    "vinicius jr.": "bra",
    "virgil van dijk": "nld",
    "vitinha": "prt",
    "weston mckennie": "usa",
    "william pacho": "ecu",
    "william saliba": "fra",
    "wilson isidor": "hai",
    "yann bisseck": "ger",
    "yoane wissa": "cdr",
}

NATION_NAME: dict[str, str] = {
    "argentina": "arg",
    "austria": "aut",
    "belgium": "bel",
    "brazil": "bra",
    "canada": "can",
    "colombia": "col",
    "cote d'ivoire": "civ",
    "ivory coast": "civ",
    "croatia": "hrv",
    "democratic republic of congo": "cdr",
    "dr congo": "cdr",
    "ecuador": "ecu",
    "egypt": "egy",
    "england": "eng",
    "france": "fra",
    "germany": "ger",
    "ghana": "gha",
    "haiti": "hai",
    "japan": "jpn",
    "mexico": "mex",
    "morocco": "mar",
    "netherlands": "nld",
    "new zealand": "nzl",
    "norway": "nor",
    "panama": "pan",
    "paraguay": "par",
    "portugal": "prt",
    "qatar": "qat",
    "scotland": "sco",
    "senegal": "sen",
    "south korea": "kor",
    "spain": "esp",
    "sweden": "swe",
    "switzerland": "che",
    "tunisia": "tun",
    "turkey": "tur",
    "united states": "usa",
    "uruguay": "ury",
    "usa": "usa",
}
